version: "3.9"

services:

  redis:
    image: redis:7-alpine
    container_name: recompute-redis
    ports:
    - "6379:6379"

  worker:
    build: .
    container_name: celery-worker
    depends_on:
    - redis
    command: celery -A orchestrator.tasks worker --loglevel=info
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
    - .:/app

  app:
    build: .
    container_name: recompute-app
    depends_on:
    - redis
    - worker
    command: python -m orchestrator.test_orchestration
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
    - .:/app
